In [25]:
import pandas as pd

list = [1,2,3,4,5,6,"string"]
disct = {
    'first':['Alash', 'Anant'],
    'second':['Sudip', 'Roshan'],
    'third':['Hari','neshant']
}
d = pd.DataFrame(disct)
print(d)
d
# new_variable = pd.Series(list)
# print(new_variable)

   first  second    third
0  Alash   Sudip     Hari
1  Anant  Roshan  neshant

   first  second    third
0  Alash   Sudip     Hari
1  Anant  Roshan  neshant

In [15]:
data = {
    'name': ['John', 'Jane', 'Jack', 'Jill'],
    'age': [20, 21, 22, 23],
    'gender': ['M', 'F', 'M', 'F']
}

df = pd.DataFrame(data)
df

   name  age gender
0  John   20      M
1  Jane   21      F
2  Jack   22      M
3  Jill   23      F

In [3]:
df = pd.read_csv("../datasets/Book1.csv")
df.head(5)

   Unnamed: 0  Years of Experience   Salary
0         NaN                  1.1  39343.0
1         NaN                  1.3  46205.0
2         NaN                  1.5  37731.0
3         NaN                  2.0  43525.0
4         NaN                  2.2  39891.0

In [7]:
df.columns.tolist()

['Unnamed: 0', 'Years of Experience', 'Salary']

In [8]:
df.dtypes

Unnamed: 0             float64
Years of Experience    float64
Salary                 float64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           0 non-null      float64
 1   Years of Experience  30 non-null     float64
 2   Salary               29 non-null     float64
dtypes: float64(3)
memory usage: 852.0 bytes

In [15]:
df.describe()

       Unnamed: 0  Years of Experience         Salary
count         0.0            30.000000      29.000000
mean          NaN             5.313333   75818.172414
std           NaN             2.837888   27880.649700
min           NaN             1.100000   37731.000000
25%           NaN             3.200000   56642.000000
50%           NaN             4.700000   64445.000000
75%           NaN             7.700000  101302.000000
max           NaN            10.500000  122391.000000

In [16]:
print(df.isnull().sum())

Unnamed: 0             30
Years of Experience     0
Salary                  1
dtype: int64

In [8]:
print(df.duplicated().sum())

0

In [10]:
print(df.corr(numeric_only=True))

                     Unnamed: 0  Years of Experience    Salary
Unnamed: 0                  NaN                  NaN       NaN
Years of Experience         NaN             1.000000  0.978212
Salary                      NaN             0.978212  1.000000

In [12]:
df = df.drop('Unnamed: 0', axis=1)
print(df)

KeyError: "['Unnamed: 0'] not found in axis"